process.env.JWT_SECRET = process.env.JWT_SECRET ?? "test-secret"
process.env.FRONTEND_URL = process.env.FRONTEND_URL ?? "http://localhost:5173"
process.env.SMTP_HOST = process.env.SMTP_HOST ?? "smtp.example.test"
process.env.SMTP_PORT = process.env.SMTP_PORT ?? "465"
process.env.SMTP_USER = process.env.SMTP_USER ?? "test"
process.env.SMTP_PASS = process.env.SMTP_PASS ?? "test"
